Adding scikit-image' Blob detection
rapidsai/cucim pull request #411
Opened 2022-09-24 17:44 UTC by monzelr

Description of the pull request can be find in #398, here a short summary:
This pull request will implement the scikit-image' blob detection.
The following helper functions moved to into blob.cu:
    - _compute_disk_overlap
    - _compute_sphere_overlap
    - _blob_overlap
    - _prune_blobs
Also, some functions to calculation the approximated hessian determinant matrix moved into _hessian_det_appx.cu (in skimage this is implemented with the help of pythran):
    - _clip
    - _integ
    - _hessian_matrix_det

Credits also to @annendominik, who helped with this implementation.

This PR will close #398 

Unit tests have been added; but because I am on a windows system; I did not test it. However; I have tested all blob detection with this script and basically like it works:

```python
from math import sqrt
import time
from skimage import data
from skimage.feature import blob_dog, blob_log, blob_doh
from skimage.color import rgb2gray

import matplotlib.pyplot as plt

print("------- skimage implementation -------")
image = data.hubble_deep_field()  # [0:500, 0:500]
image_gray = rgb2gray(image)

_start_time = time.time()
blobs_log = blob_log(image_gray, max_sigma=30, num_sigma=10, threshold=.1)
print("elapsed time blobs_log: %3.3f seconds" % (time.time() - _start_time))

# Compute radii in the 3rd column.
blobs_log[:, 2] = blobs_log[:, 2] * sqrt(2)

_start_time = time.time()
blobs_dog = blob_dog(image_gray, max_sigma=30, threshold=.1)
print("elapsed time blob_dog: %3.3f seconds" % (time.time() - _start_time))
blobs_dog[:, 2] = blobs_dog[:, 2] * sqrt(2)

_start_time = time.time()
blobs_doh = blob_doh(image_gray, max_sigma=30, threshold=.01)
print("elapsed time blobs_doh: %3.3f seconds" % (time.time() - _start_time))

blobs_list = [blobs_log, blobs_dog, blobs_doh]
colors = ['yellow', 'lime', 'red']
titles = ['Laplacian of Gaussian', 'Difference of Gaussian',
          'Determinant of Hessian']
sequence = zip(blobs_list, colors, titles)

fig, axes = plt.subplots(1, 3, figsize=(9, 3), sharex=True, sharey=True)
ax = axes.ravel()

for idx, (blobs, color, title) in enumerate(sequence):
    ax[idx].set_title(title)
    ax[idx].imshow(image)
    for blob in blobs:
        y, x, r = blob
        c = plt.Circle((x, y), r, color=color, linewidth=2, fill=False)
        ax[idx].add_patch(c)
    ax[idx].set_axis_off()
plt.tight_layout()
print()

print("------- cucim.skimage implementation -------")
from cucim.skimage.feature import blob_dog, blob_log, blob_doh
from cucim.skimage.color import rgb2gray
import cupy as cp

gpu_sync = cp.cuda.stream.get_current_stream().synchronize

image = data.hubble_deep_field()  # [0:500, 0:500]
image_gray = rgb2gray(cp.asarray(image))
print("dtype: %s" % str(image_gray.dtype))

blob_log(image_gray, max_sigma=30, num_sigma=10, threshold=.1)  # cache function
gpu_sync()
_start_time = time.time()
blobs_log = blob_log(image_gray, max_sigma=30, num_sigma=10, threshold=.1)
gpu_sync()
print("elapsed time blobs_log: %3.3f seconds" % (time.time() - _start_time))

# Compute radii in the 3rd column.
blobs_log[:, 2] = blobs_log[:, 2] * sqrt(2)

blob_dog(image_gray, max_sigma=30, threshold=.1)
gpu_sync()
_start_time = time.time()
blobs_dog = blob_dog(image_gray, max_sigma=30, threshold=.1)
gpu_sync()
print("elapsed time blob_dog: %3.3f seconds" % (time.time() - _start_time))
blobs_dog[:, 2] = blobs_dog[:, 2] * sqrt(2)

blob_doh(image_gray, max_sigma=30, threshold=.01)
gpu_sync()
_start_time = time.time()
blobs_doh = blob_doh(image_gray, max_sigma=30, threshold=.01)
gpu_sync()
print("elapsed time blobs_doh: %3.3f seconds" % (time.time() - _start_time))

image_gray = image_gray.astype(cp.float64)
print("dtype: %s" % str(image_gray.dtype))

blob_log(image_gray, max_sigma=30, num_sigma=10, threshold=.1)  # cache function
gpu_sync()
_start_time = time.time()
blobs_log = blob_log(image_gray, max_sigma=30, num_sigma=10, threshold=.1)
gpu_sync()
print("elapsed time blobs_log: %3.3f seconds" % (time.time() - _start_time))

# Compute radii in the 3rd column.
blobs_log[:, 2] = blobs_log[:, 2] * sqrt(2)

try:
    blob_dog(image_gray, max_sigma=30, threshold=.1)
    gpu_sync()
    _start_time = time.time()
    blobs_dog = blob_dog(image_gray, max_sigma=30, threshold=.1)
    gpu_sync()
    print("elapsed time blob_dog: %3.3f seconds" % (time.time() - _start_time))
    blobs_dog[:, 2] = blobs_dog[:, 2] * sqrt(2)
except Exception as e:
    import sys
    print(e, file=sys.stderr)

blob_doh(image_gray, max_sigma=30, threshold=.01)
gpu_sync()
_start_time = time.time()
blobs_doh = blob_doh(image_gray, max_sigma=30, threshold=.01)
gpu_sync()
print("elapsed time blobs_doh: %3.3f seconds" % (time.time() - _start_time))

blobs_list = [cp.asnumpy(blobs_log), cp.asnumpy(blobs_dog), cp.asnumpy(blobs_doh)]
colors = ['yellow', 'lime', 'red']
titles = ['Laplacian of Gaussian', 'Difference of Gaussian',
          'Determinant of Hessian']
sequence = zip(blobs_list, colors, titles)

fig_cucim, axes_cucim = plt.subplots(1, 3, figsize=(9, 3), sharex=True, sharey=True)
ax = axes_cucim.ravel()

for idx, (blobs, color, title) in enumerate(sequence):
    ax[idx].set_title(title)
    ax[idx].imshow(image)
    for blob in blobs:
        y, x, r = blob
        c = plt.Circle((x, y), r, color=color, linewidth=2, fill=False)
        ax[idx].add_patch(c)
    ax[idx].set_axis_off()
plt.tight_layout()

plt.show()
```

However, for dtype=`cp.float64` I got the following error:
```
Traceback (most recent call last):
  File "C:/Users/RuneMonzel/autolucid/01_python_src/dev/annen/test.py", line 100, in <module>
    blob_dog(image_gray, max_sigma=30, threshold=.1)
  File "c:\users\runemonzel\cucim\python\cucim\src\cucim\skimage\feature\blob.py", line 320, in blob_dog
    gaussian_images = [gaussian(image, s, mode='reflect') for s in sigma_list]
  File "c:\users\runemonzel\cucim\python\cucim\src\cucim\skimage\feature\blob.py", line 320, in <listcomp>
    gaussian_images = [gaussian(image, s, mode='reflect') for s in sigma_list]
  File "c:\users\runemonzel\cucim\python\cucim\src\cucim\skimage\_shared\utils.py", line 294, in fixed_func
    return func(*args, **kwargs)
  File "c:\users\runemonzel\cucim\python\cucim\src\cucim\skimage\_shared\filters.py", line 141, in gaussian
    ndi.gaussian_filter(image, sigma, output=output, mode=mode, cval=cval,
  File "c:\users\runemonzel\cucim\python\cucim\src\cucim\skimage\_vendored\_ndimage_filters.py", line 419, in gaussian_filter
    return _run_1d_correlates(input, list(zip(sigmas, orders)), get, output,
  File "c:\users\runemonzel\cucim\python\cucim\src\cucim\skimage\_vendored\_ndimage_filters.py", line 248, in _run_1d_correlates
    return _filters_core._run_1d_filters(
  File "c:\users\runemonzel\cucim\python\cucim\src\cucim\skimage\_vendored\_ndimage_filters_core.py", line 100, in _run_1d_filters
    fltr(input, arg, axis, temp, mode, cval, origin, **filter_kwargs)
  File "c:\users\runemonzel\cucim\python\cucim\src\cucim\skimage\_vendored\_ndimage_filters.py", line 112, in correlate1d
    return _correlate_or_convolve1d(
  File "c:\users\runemonzel\cucim\python\cucim\src\cucim\skimage\_vendored\_ndimage_filters.py", line 204, in _correlate_or_convolve1d
    out = _shmem_convolve1d(input, weights, axis=axis, output=output,
  File "c:\users\runemonzel\cucim\python\cucim\src\cucim\skimage\filters\_separable_filtering.py", line 967, in _shmem_convolve1d
    conv_axis_kernel, block, patch_per_block = _get_separable_conv_kernel(
  File "cupy\_util.pyx", line 67, in cupy._util.memoize.decorator.ret
  File "c:\users\runemonzel\cucim\python\cucim\src\cucim\skimage\filters\_separable_filtering.py", line 858, in _get_separable_conv_kernel
    return m.get_function(func_name), block, patch_per_block
  File "cupy\_core\raw.pyx", line 485, in cupy._core.raw.RawModule.get_function
  File "cupy\_core\raw.pyx", line 96, in cupy._core.raw.RawKernel.kernel.__get__
  File "cupy\_core\raw.pyx", line 113, in cupy._core.raw.RawKernel._kernel
  File "cupy\_util.pyx", line 67,  [...]

2022-09-24 17:44 UTC, GPUtester commented
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

2022-09-25 22:13 UTC, grlee77 commented
Thanks @monzelr and @annendominik for working on this. I have not reviewed the new kernels yet, but here are two general suggestions:

- can you [rename the branch](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) you made the PR from to something like `add-blob-detection` so that it doesn't clash with the main `branch-22.10` development branch name? Having unique names will also make it easier on your end if you ever want to have multiple development branches in progress at the same time.

- can we remove the `cucim.skimage.draw` module from this PR to keep things concise? It looks like they are only needed here to generate test data for the blob detection. It is fine to just generate the disks/ellipsoids on the CPU in the test code and explicitly transfer to the GPU with `cupy.asarray`. We can discuss separately in another PR if you want to add `draw` functions to cuCIM, but so far we have not tried to provide that module.

2022-09-25 22:44 UTC, grlee77 commented
Also, regarding benchmarking, it is good that you are calling synchronize appropriately. However, you may be interested in [`cupyx.profiler.benchmark` from CuPy](https://docs.cupy.dev/en/stable/reference/generated/cupyx.profiler.benchmark.html#cupyx-profiler-benchmark). It will automatically take care of that for you and average over a specified number of iterations or duration (via `max_duration` in seconds). 

For example
```Python
gpu_sync()
_start_time = time.time()
blobs_log = blob_log(image_gray, max_sigma=30, num_sigma=10, threshold=.1)
gpu_sync()
print("elapsed time blobs_log: %3.3f seconds" % (time.time() - _start_time))
```
could be written as
```python
kwargs = dict(max_sigma=30, num_sigma=10, threshold=0.1)
perf = benchmark(blob_log, (image_gray,), kwargs=kwargs, n_warmup=10, n_repeat=1000, max_duration=2)
print(f"elapsed time blobs_log: {perf.gpu_times.mean():0.5f} s +/- {perf.gpu_times.std():0.5f} s")
```

2022-09-25 22:51 UTC, grlee77 commented
> @grlee77
> Any thoughts on that??

Running the example you provided I saw the following on my system:
```
ptxas error   : Entry function 'correlate_s135_2d_ax0_reflect_Tdouble_Wdouble_Ddouble_patch9_halo9' uses too much shared data (0xd800 bytes, 0xc000 max)
```
which is a bug I also recently encountered and reported in #408. #409 fixes it, and will hopefully be reviewed and merged soon.

2022-09-26 00:30 UTC, grlee77 requested changes
I suggested some changes to `test_blob.py` that were needed to get it to work on my system and to remove the need for `cucim.skimage.draw` in this PR.

I will review the actual CUDA kernel code soon, but the tests are already passing which is great!

2022-09-26 00:30 UTC, grlee77 commented on python/cucim/src/cucim/skimage/feature/tests/test_blob.py
> +                        1./math.pi * (2 * math.acos(1./2) - math.sqrt(3)/2.))
remove this test since we do not have a standalone `_blob_overlap` function to test

```suggestion
```

2022-09-26 00:30 UTC, grlee77 commented on python/cucim/src/cucim/skimage/feature/tests/test_blob.py
> +    assert_almost_equal(overlap, 0.48125)
remove this test since we do not have a standalone `_blob_overlap` function to test

```suggestion
```

2022-09-26 00:30 UTC, grlee77 commented on python/cucim/src/cucim/skimage/feature/tests/test_blob.py
> +from cupy.testing import assert_almost_equal
```suggestion
```
`assert_almost_equal` is not available in CuPy (could import from NumPy and copy scalar back to the host first, but we don't need this function at all except in the test cases I suggested deleting below)

2022-09-26 00:30 UTC, grlee77 commented on python/cucim/src/cucim/skimage/feature/tests/test_blob.py
> +from cucim.skimage.feature.blob import _blob_overlap
```suggestion
```

Does not exist as a standalone Python function in this iteration. You could make one just for testing purposes, but just testing the higher-level functions may be sufficient.

2022-09-26 00:30 UTC, grlee77 commented on python/cucim/src/cucim/skimage/feature/tests/test_blob.py
> +import pytest
can just generate disks and ellipsoids on the CPU

```suggestion
import numpy as np
import pytest
from skimage.draw import disk, ellipsoid
```

2022-09-26 00:30 UTC, grlee77 commented on python/cucim/src/cucim/skimage/feature/tests/test_blob.py
> +from cucim.skimage.draw.draw3d import ellipsoid
```suggestion
```

2022-09-26 00:30 UTC, grlee77 commented on python/cucim/src/cucim/skimage/feature/tests/test_blob.py
> +    img = cp.ones((512, 512), dtype=dtype)
```suggestion
    img = np.ones((512, 512), dtype=dtype)
```

2022-09-26 00:30 UTC, grlee77 commented on python/cucim/src/cucim/skimage/feature/tests/test_blob.py
> +    blobs = blob_dog(
```suggestion
    img = cp.asarray(img)
    blobs = blob_dog(
```

2022-09-26 00:30 UTC, grlee77 commented on python/cucim/src/cucim/skimage/feature/tests/test_blob.py
> +@pytest.mark.parametrize(
add convenience wrapper to give CuPy output for ellipsoid
```suggestion
def ellipsoid(a, b, c):
    return cp.asarray(ellipsoid_cpu(a, b, c))


@pytest.mark.parametrize(
```

2022-09-26 00:30 UTC, grlee77 commented on python/cucim/src/cucim/skimage/feature/tests/test_blob.py
> +    img[xs, ys] = 255
```suggestion
    img = np.ones((512, 512))
    xs, ys = disk((5, 5), 5)
    img[xs, ys] = 255
    img = cp.asarray(img)
```

2022-09-26 00:30 UTC, grlee77 commented on python/cucim/src/cucim/skimage/feature/tests/test_blob.py
> +    img = cp.ones((256, 256), dtype=dtype)
```suggestion
    img = np.ones((256, 256), dtype=dtype)
```

2022-09-26 00:30 UTC, grlee77 commented on python/cucim/src/cucim/skimage/feature/tests/test_blob.py
> +    blobs = blob_log(img, min_sigma=5, max_sigma=20, threshold=threshold,
```suggestion
    img = cp.asarray(img)
    blobs = blob_log(img, min_sigma=5, max_sigma=20, threshold=threshold,
```

2022-09-26 00:30 UTC, grlee77 commented on python/cucim/src/cucim/skimage/feature/tests/test_blob.py
> +    img = cp.ones((11, 11))
```suggestion
    img = np.ones((11, 11))
```

2022-09-26 00:30 UTC, grlee77 commented on python/cucim/src/cucim/skimage/feature/tests/test_blob.py
> +    blob_log(img, max_sigma=20, num_sigma=10, threshold=.1)
```suggestion
    blob_log(cp.asarray(img), max_sigma=20, num_sigma=10, threshold=.1)
```

2022-09-26 00:30 UTC, grlee77 commented on python/cucim/src/cucim/skimage/feature/tests/test_blob.py
> +    img[xs, ys] = 255
```suggestion
    img = np.ones((512, 512))
    xs, ys = disk((5, 5), 5)
    img[xs, ys] = 255
    img = cp.asarray(img)
```

2022-09-26 00:30 UTC, grlee77 commented on python/cucim/src/cucim/skimage/feature/tests/test_blob.py
> +    img = cp.ones((512, 512), dtype=dtype)
```suggestion
    img = np.ones((512, 512), dtype=dtype)
```

2022-09-26 00:30 UTC, grlee77 commented on python/cucim/src/cucim/skimage/feature/tests/test_blob.py
> +    blobs = blob_doh(
```suggestion

    img = cp.asarray(img)
    blobs = blob_doh(
```

2022-09-26 00:30 UTC, grlee77 commented on python/cucim/src/cucim/skimage/feature/tests/test_blob.py
> +    img = cp.ones((512, 512), dtype=cp.uint8)
```suggestion
    img = np.ones((512, 512), dtype=cp.uint8)
```

2022-09-26 00:30 UTC, grlee77 commented on python/cucim/src/cucim/skimage/feature/tests/test_blob.py
> +    blobs = blob_doh(
```suggestion
    img = cp.asarray(img)
    blobs = blob_doh(
```

2022-09-26 00:30 UTC, grlee77 commented on python/cucim/src/cucim/skimage/feature/tests/test_blob.py
> +    img = cp.ones((256, 256), dtype=cp.uint8)
```suggestion
    img = np.ones((256, 256), dtype=cp.uint8)
```

2022-09-26 00:30 UTC, grlee77 commented on python/cucim/src/cucim/skimage/feature/tests/test_blob.py
> +    blobs = blob_doh(
```suggestion
    img = cp.asarray(img)
    blobs = blob_doh(
```

2022-09-26 07:15 UTC, closed without merging